import { Outfit } from "next/font/google";
import "./globals.css";
import "@liveblocks/react-ui/styles.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';
import { Toaster } from "@/components/ui/toaster";
// import { NotificationsProvider } from "./NotificationProvider";

const geistSans = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Outfit({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Flowly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClerkLoading>
            <div className="mx-[30%] my-[40%] md:my-[20%] md:mx-[40%]">
              <div className="card">
                <div className="loader">
                  <p className="flex">Loading <span className="md:hidden">...</span></p>
                  <div className="words">
                    <span className="word">Spaces</span>
                    <span className="word">Work</span>
                    <span className="word">Notes</span>
                    <span className="word">Data</span>
                  </div>
                </div>
              </div>
            </div>
            <span className="hidden md:flex bottom-2 justify-center text-slate-800 text-md p-2 font-semibold">
              Step into Flowly — Collaborate, create, and connect seamlessly.
            </span>
          </ClerkLoading>

          <ClerkLoaded>
            <Toaster />
            {children}
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
